import { useMemo } from 'react'
import DOMPurify from 'dompurify'

interface BlogPostContentProps {
  content: string
}

// Check whether the content has HTML tags (like <p>, <h2>, <table>, etc.)
function isHtmlContent(str: string): boolean {
  if (!str) return false
  // Check for common HTML tags generated by WYSIWYG
  return /<\/?[a-z][\s\S]*>/i.test(str)
}

export function BlogPostContent({ content }: BlogPostContentProps) {
  const isHtml = useMemo(() => isHtmlContent(content), [content])

  const sanitizedHtml = useMemo(() => {
    if (!isHtml) return ''
    return DOMPurify.sanitize(content, {
      ALLOWED_TAGS: [
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'p',
        'span',
        'strong',
        'b',
        'em',
        'i',
        'u',
        's',
        'strike',
        'blockquote',
        'ul',
        'ol',
        'li',
        'a',
        'img',
        'table',
        'thead',
        'tbody',
        'tr',
        'th',
        'td',
        'hr',
        'br',
        'code',
        'pre',
        'div',
      ],
      ALLOWED_ATTR: [
        'href',
        'src',
        'alt',
        'title',
        'class',
        'target',
        'rel',
        'style',
        'data-color',
        'width',
        'height',
        'colspan',
        'rowspan',
      ],
      ADD_ATTR: ['target', 'rel', 'data-color'],
      ADD_TAGS: ['mark'],
      FORBID_TAGS: ['script', 'iframe', 'object', 'embed'],
    })
  }, [content, isHtml])

  if (!content) {
    return null
  }

  // If plain text (historical posts created before WYSIWYG), render with whitespace-pre-line
  if (!isHtml) {
    return (
      <div className="prose prose-slate max-w-none text-foreground/90 text-base md:text-lg leading-relaxed whitespace-pre-line space-y-6">
        {content}
      </div>
    )
  }

  // If rich HTML content, render sanitized HTML inside a styled container
  return (
    <div
      className="ibisoft-blog-content text-foreground/90 text-base md:text-lg leading-relaxed"
      dangerouslySetInnerHTML={{ __html: sanitizedHtml }}
    />
  )
}
